name: Jekyll

on: 
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Ruby Setup
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.3.7

      - name: Building the Jekyll site
        run: bundle exec jekyll build
